name: App Azure ARM

on:
  push:
    branches: ['main']
    paths: ['Infrastructure/app.bicep', 'Infrastructure/app.azuredeploy.parameters.json', '.github/workflows/app-docker-image.yml', '.github/workflows/app-bicep.yml']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./Infrastructure/app.bicep
        parameters: ./Infrastructure/app.azuredeploy.parameters.json
        failOnStdErr: false
