name: Deploy a App Docker image

on:
  push:
    branches: ['main']
    paths: ['CourtStack.CTC.Workshop-After', '.github/workflows/app-docker-image.yml', '.github/workflows/deploy-app.yml']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}.CourtStack.CTC.Workshop

jobs:
  deploy-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Docker image
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'CourtStack-Web'
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main
